#############################################################################
# Makefile for building: RA3_Cheat
# Generated by qmake (3.0) (Qt 5.7.1)
# Project:  RA3_Cheat.pro
# Template: app
# Command: F:\QT\5.7\mingw53_32\bin\qmake.exe -spec win32-g++ -o Makefile RA3_Cheat.pro
#############################################################################

MAKEFILE      = Makefile

first: release
install: release-install
uninstall: release-uninstall
QMAKE         = F:\QT\5.7\mingw53_32\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = copy /y
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = copy /y
INSTALL_PROGRAM = copy /y
INSTALL_DIR   = xcopy /s /q /y /i
DEL_FILE      = del
SYMLINK       = $(QMAKE) -install ln -f -s
DEL_DIR       = rmdir
MOVE          = move
SUBTARGETS    =  \
		release \
		debug


release: FORCE
	$(MAKE) -f $(MAKEFILE).Release
release-make_first: FORCE
	$(MAKE) -f $(MAKEFILE).Release 
release-all: FORCE
	$(MAKE) -f $(MAKEFILE).Release all
release-clean: FORCE
	$(MAKE) -f $(MAKEFILE).Release clean
release-distclean: FORCE
	$(MAKE) -f $(MAKEFILE).Release distclean
release-install: FORCE
	$(MAKE) -f $(MAKEFILE).Release install
release-uninstall: FORCE
	$(MAKE) -f $(MAKEFILE).Release uninstall
debug: FORCE
	$(MAKE) -f $(MAKEFILE).Debug
debug-make_first: FORCE
	$(MAKE) -f $(MAKEFILE).Debug 
debug-all: FORCE
	$(MAKE) -f $(MAKEFILE).Debug all
debug-clean: FORCE
	$(MAKE) -f $(MAKEFILE).Debug clean
debug-distclean: FORCE
	$(MAKE) -f $(MAKEFILE).Debug distclean
debug-install: FORCE
	$(MAKE) -f $(MAKEFILE).Debug install
debug-uninstall: FORCE
	$(MAKE) -f $(MAKEFILE).Debug uninstall

Makefile: RA3_Cheat.pro F:/QT/5.7/mingw53_32/mkspecs/win32-g++/qmake.conf F:/QT/5.7/mingw53_32/mkspecs/features/spec_pre.prf \
		F:/QT/5.7/mingw53_32/mkspecs/qdevice.pri \
		F:/QT/5.7/mingw53_32/mkspecs/features/device_config.prf \
		F:/QT/5.7/mingw53_32/mkspecs/common/angle.conf \
		F:/QT/5.7/mingw53_32/mkspecs/qconfig.pri \
		F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_3dcore.pri \
		F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_3dcore_private.pri \
		F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_3dextras.pri \
		F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_3dextras_private.pri \
		F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_3dinput.pri \
		F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_3dinput_private.pri \
		F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_3dlogic.pri \
		F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_3dlogic_private.pri \
		F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_3dquick.pri \
		F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_3dquick_private.pri \
		F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_3dquickextras.pri \
		F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_3dquickinput.pri \
		F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_3dquickrender.pri \
		F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_3drender.pri \
		F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_3drender_private.pri \
		F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_axbase.pri \
		F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_axbase_private.pri \
		F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_axcontainer.pri \
		F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_axcontainer_private.pri \
		F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_axserver.pri \
		F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_axserver_private.pri \
		F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_bluetooth.pri \
		F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_bluetooth_private.pri \
		F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_bootstrap_private.pri \
		F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_clucene_private.pri \
		F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_concurrent.pri \
		F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_concurrent_private.pri \
		F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_core.pri \
		F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_core_private.pri \
		F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_dbus.pri \
		F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_dbus_private.pri \
		F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_designer.pri \
		F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_designer_private.pri \
		F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_designercomponents_private.pri \
		F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_gamepad.pri \
		F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_gamepad_private.pri \
		F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_gui.pri \
		F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_gui_private.pri \
		F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_help.pri \
		F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_help_private.pri \
		F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_location.pri \
		F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_location_private.pri \
		F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_multimedia.pri \
		F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_multimedia_private.pri \
		F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_multimediawidgets.pri \
		F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_network.pri \
		F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_network_private.pri \
		F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_nfc.pri \
		F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_nfc_private.pri \
		F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_opengl.pri \
		F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_opengl_private.pri \
		F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_openglextensions.pri \
		F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_openglextensions_private.pri \
		F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_platformsupport_private.pri \
		F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_positioning.pri \
		F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_positioning_private.pri \
		F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_printsupport.pri \
		F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_printsupport_private.pri \
		F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_purchasing.pri \
		F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_purchasing_private.pri \
		F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_qml.pri \
		F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_qml_private.pri \
		F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_qmldebug_private.pri \
		F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_qmltest.pri \
		F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_qmltest_private.pri \
		F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_quick.pri \
		F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_quick_private.pri \
		F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_quickcontrols2.pri \
		F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_quickparticles_private.pri \
		F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_quickwidgets.pri \
		F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_script.pri \
		F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_script_private.pri \
		F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_scripttools.pri \
		F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_scripttools_private.pri \
		F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_scxml.pri \
		F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_scxml_private.pri \
		F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_sensors.pri \
		F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_sensors_private.pri \
		F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_serialbus.pri \
		F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_serialbus_private.pri \
		F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_serialport.pri \
		F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_serialport_private.pri \
		F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_sql.pri \
		F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_sql_private.pri \
		F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_svg.pri \
		F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_svg_private.pri \
		F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_testlib.pri \
		F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_testlib_private.pri \
		F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_uiplugin.pri \
		F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_uitools.pri \
		F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_uitools_private.pri \
		F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_webchannel.pri \
		F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_webchannel_private.pri \
		F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_websockets.pri \
		F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_websockets_private.pri \
		F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_widgets.pri \
		F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_widgets_private.pri \
		F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_winextras.pri \
		F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_winextras_private.pri \
		F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_xml.pri \
		F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_xml_private.pri \
		F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_xmlpatterns.pri \
		F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		F:/QT/5.7/mingw53_32/mkspecs/features/qt_functions.prf \
		F:/QT/5.7/mingw53_32/mkspecs/features/qt_config.prf \
		F:/QT/5.7/mingw53_32/mkspecs/features/win32/qt_config.prf \
		F:/QT/5.7/mingw53_32/mkspecs/win32-g++/qmake.conf \
		F:/QT/5.7/mingw53_32/mkspecs/features/spec_post.prf \
		.qmake.stash \
		F:/QT/5.7/mingw53_32/mkspecs/features/exclusive_builds.prf \
		F:/QT/5.7/mingw53_32/mkspecs/features/toolchain.prf \
		F:/QT/5.7/mingw53_32/mkspecs/features/default_pre.prf \
		F:/QT/5.7/mingw53_32/mkspecs/features/win32/default_pre.prf \
		F:/QT/5.7/mingw53_32/mkspecs/features/resolve_config.prf \
		F:/QT/5.7/mingw53_32/mkspecs/features/exclusive_builds_post.prf \
		F:/QT/5.7/mingw53_32/mkspecs/features/default_post.prf \
		F:/QT/5.7/mingw53_32/mkspecs/features/win32/rtti.prf \
		F:/QT/5.7/mingw53_32/mkspecs/features/precompile_header.prf \
		F:/QT/5.7/mingw53_32/mkspecs/features/warn_on.prf \
		F:/QT/5.7/mingw53_32/mkspecs/features/qt.prf \
		F:/QT/5.7/mingw53_32/mkspecs/features/resources.prf \
		F:/QT/5.7/mingw53_32/mkspecs/features/moc.prf \
		F:/QT/5.7/mingw53_32/mkspecs/features/win32/opengl.prf \
		F:/QT/5.7/mingw53_32/mkspecs/features/uic.prf \
		F:/QT/5.7/mingw53_32/mkspecs/features/file_copies.prf \
		F:/QT/5.7/mingw53_32/mkspecs/features/win32/windows.prf \
		F:/QT/5.7/mingw53_32/mkspecs/features/testcase_targets.prf \
		F:/QT/5.7/mingw53_32/mkspecs/features/exceptions.prf \
		F:/QT/5.7/mingw53_32/mkspecs/features/yacc.prf \
		F:/QT/5.7/mingw53_32/mkspecs/features/lex.prf \
		RA3_Cheat.pro \
		F:/QT/5.7/mingw53_32/lib/qtmain.prl \
		F:/QT/5.7/mingw53_32/lib/Qt5Widgets.prl \
		F:/QT/5.7/mingw53_32/lib/Qt5Gui.prl \
		F:/QT/5.7/mingw53_32/lib/Qt5Core.prl
	$(QMAKE) -spec win32-g++ -o Makefile RA3_Cheat.pro
F:/QT/5.7/mingw53_32/mkspecs/features/spec_pre.prf:
F:/QT/5.7/mingw53_32/mkspecs/qdevice.pri:
F:/QT/5.7/mingw53_32/mkspecs/features/device_config.prf:
F:/QT/5.7/mingw53_32/mkspecs/common/angle.conf:
F:/QT/5.7/mingw53_32/mkspecs/qconfig.pri:
F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_3dcore.pri:
F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_3dcore_private.pri:
F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_3dextras.pri:
F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_3dextras_private.pri:
F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_3dinput.pri:
F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_3dinput_private.pri:
F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_3dlogic.pri:
F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_3dlogic_private.pri:
F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_3dquick.pri:
F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_3dquick_private.pri:
F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_3dquickextras.pri:
F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_3dquickextras_private.pri:
F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_3dquickinput.pri:
F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_3dquickinput_private.pri:
F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_3dquickrender.pri:
F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_3dquickrender_private.pri:
F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_3drender.pri:
F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_3drender_private.pri:
F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_axbase.pri:
F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_axbase_private.pri:
F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_axcontainer.pri:
F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_axcontainer_private.pri:
F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_axserver.pri:
F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_axserver_private.pri:
F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_bluetooth.pri:
F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_bluetooth_private.pri:
F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_bootstrap_private.pri:
F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_clucene_private.pri:
F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_concurrent.pri:
F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_concurrent_private.pri:
F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_core.pri:
F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_core_private.pri:
F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_dbus.pri:
F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_dbus_private.pri:
F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_designer.pri:
F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_designer_private.pri:
F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_designercomponents_private.pri:
F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_gamepad.pri:
F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_gamepad_private.pri:
F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_gui.pri:
F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_gui_private.pri:
F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_help.pri:
F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_help_private.pri:
F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_location.pri:
F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_location_private.pri:
F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_multimedia.pri:
F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_multimedia_private.pri:
F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_multimediawidgets.pri:
F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_network.pri:
F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_network_private.pri:
F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_nfc.pri:
F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_nfc_private.pri:
F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_opengl.pri:
F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_opengl_private.pri:
F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_openglextensions.pri:
F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_openglextensions_private.pri:
F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_packetprotocol_private.pri:
F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_platformsupport_private.pri:
F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_positioning.pri:
F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_positioning_private.pri:
F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_printsupport.pri:
F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_printsupport_private.pri:
F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_purchasing.pri:
F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_purchasing_private.pri:
F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_qml.pri:
F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_qml_private.pri:
F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_qmldebug_private.pri:
F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_qmldevtools_private.pri:
F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_qmltest.pri:
F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_qmltest_private.pri:
F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_quick.pri:
F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_quick_private.pri:
F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_quickcontrols2.pri:
F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_quickparticles_private.pri:
F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_quickwidgets.pri:
F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_quickwidgets_private.pri:
F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_script.pri:
F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_script_private.pri:
F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_scripttools.pri:
F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_scripttools_private.pri:
F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_scxml.pri:
F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_scxml_private.pri:
F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_sensors.pri:
F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_sensors_private.pri:
F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_serialbus.pri:
F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_serialbus_private.pri:
F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_serialport.pri:
F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_serialport_private.pri:
F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_sql.pri:
F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_sql_private.pri:
F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_svg.pri:
F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_svg_private.pri:
F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_testlib.pri:
F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_testlib_private.pri:
F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_uiplugin.pri:
F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_uitools.pri:
F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_uitools_private.pri:
F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_webchannel.pri:
F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_webchannel_private.pri:
F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_websockets.pri:
F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_websockets_private.pri:
F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_widgets.pri:
F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_widgets_private.pri:
F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_winextras.pri:
F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_winextras_private.pri:
F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_xml.pri:
F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_xml_private.pri:
F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_xmlpatterns.pri:
F:/QT/5.7/mingw53_32/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
F:/QT/5.7/mingw53_32/mkspecs/features/qt_functions.prf:
F:/QT/5.7/mingw53_32/mkspecs/features/qt_config.prf:
F:/QT/5.7/mingw53_32/mkspecs/features/win32/qt_config.prf:
F:/QT/5.7/mingw53_32/mkspecs/win32-g++/qmake.conf:
F:/QT/5.7/mingw53_32/mkspecs/features/spec_post.prf:
.qmake.stash:
F:/QT/5.7/mingw53_32/mkspecs/features/exclusive_builds.prf:
F:/QT/5.7/mingw53_32/mkspecs/features/toolchain.prf:
F:/QT/5.7/mingw53_32/mkspecs/features/default_pre.prf:
F:/QT/5.7/mingw53_32/mkspecs/features/win32/default_pre.prf:
F:/QT/5.7/mingw53_32/mkspecs/features/resolve_config.prf:
F:/QT/5.7/mingw53_32/mkspecs/features/exclusive_builds_post.prf:
F:/QT/5.7/mingw53_32/mkspecs/features/default_post.prf:
F:/QT/5.7/mingw53_32/mkspecs/features/win32/rtti.prf:
F:/QT/5.7/mingw53_32/mkspecs/features/precompile_header.prf:
F:/QT/5.7/mingw53_32/mkspecs/features/warn_on.prf:
F:/QT/5.7/mingw53_32/mkspecs/features/qt.prf:
F:/QT/5.7/mingw53_32/mkspecs/features/resources.prf:
F:/QT/5.7/mingw53_32/mkspecs/features/moc.prf:
F:/QT/5.7/mingw53_32/mkspecs/features/win32/opengl.prf:
F:/QT/5.7/mingw53_32/mkspecs/features/uic.prf:
F:/QT/5.7/mingw53_32/mkspecs/features/file_copies.prf:
F:/QT/5.7/mingw53_32/mkspecs/features/win32/windows.prf:
F:/QT/5.7/mingw53_32/mkspecs/features/testcase_targets.prf:
F:/QT/5.7/mingw53_32/mkspecs/features/exceptions.prf:
F:/QT/5.7/mingw53_32/mkspecs/features/yacc.prf:
F:/QT/5.7/mingw53_32/mkspecs/features/lex.prf:
RA3_Cheat.pro:
F:/QT/5.7/mingw53_32/lib/qtmain.prl:
F:/QT/5.7/mingw53_32/lib/Qt5Widgets.prl:
F:/QT/5.7/mingw53_32/lib/Qt5Gui.prl:
F:/QT/5.7/mingw53_32/lib/Qt5Core.prl:
qmake: FORCE
	@$(QMAKE) -spec win32-g++ -o Makefile RA3_Cheat.pro

qmake_all: FORCE

make_first: release-make_first debug-make_first  FORCE
all: release-all debug-all  FORCE
clean: release-clean debug-clean  FORCE
distclean: release-distclean debug-distclean  FORCE
	-$(DEL_FILE) Makefile
	-$(DEL_FILE) .qmake.stash

release-mocclean:
	$(MAKE) -f $(MAKEFILE).Release mocclean
debug-mocclean:
	$(MAKE) -f $(MAKEFILE).Debug mocclean
mocclean: release-mocclean debug-mocclean

release-mocables:
	$(MAKE) -f $(MAKEFILE).Release mocables
debug-mocables:
	$(MAKE) -f $(MAKEFILE).Debug mocables
mocables: release-mocables debug-mocables

check: first

benchmark: first
FORCE:

$(MAKEFILE).Release: Makefile
$(MAKEFILE).Debug: Makefile
